language: python
python:
 - "3.6.6"

install:
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install coverage

script:
- pytest --with-coverage

after_success:
- "codecov"
- coveralls

branches: 
 - ft-correctionsbranch-161962988

notifications:

  email: false